# Generated by Django 4.2.4 on 2023-08-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='epic',
        ),
        migrations.DeleteModel(
            name='Epic',
        ),
    ]
