# Generated by Django 4.2.4 on 2023-08-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
