# Generated by Django 4.2.4 on 2023-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0010_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='actors',
            field=models.ManyToManyField(related_name='staff', to='reqspec.actor'),
        ),
    ]
