# Generated by Django 4.2.4 on 2023-08-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0011_alter_staff_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='staff',
            field=models.ManyToManyField(related_name='actors', to='reqspec.staff'),
        ),
    ]
