# Generated by Django 4.2.4 on 2023-08-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0013_staff_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='reqspec.project'),
            preserve_default=False,
        ),
    ]
