# Generated by Django 4.2.4 on 2023-08-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0015_remove_usecase_project_usecase_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='name',
        ),
    ]
