# Generated by Django 4.2.4 on 2023-08-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reqspec', '0016_rename_name_actor_role_rename_role_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='specification',
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='use_case',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='reqspec.usecase'),
            preserve_default=False,
        ),
    ]
